testName: ceshi1111233245
zuul:
  routes:
    api-a:
      ### 以 /api-member/访问转发到会员服务
      path: /configSserver/**
      serviceId: config-server
    api-b:
      ### 以 /api-order/访问转发到订单服务
      path: /testConfig/**
      serviceId: test-config
